server.port=8083
spring.application.name=payment-service

spring.datasource.url=jdbc:postgresql://localhost:5432/paymentsDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

svc.wallet.url=
svc.merchant.url=
svc.notify.url=

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
